services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8888:8888"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - server

networks:
  default:
    name: networkchatroom